---
- name: Deploy Percona Node
  hosts: percona_servers
  become: true

  tasks:
   - name: Pull Percona Image
     docker_image:
       name: percona/percona-xtradb-cluster:5.7
       source: pull

   - name: Deploy Percona Container
     docker_container:
       name: pxc_node1
       image: percona/percona-xtradb-cluster:5.7
       env:
         MYSQL_ALLOW_EMPTY_PASSWORD=yes
         MYSQL_ROOT_PASSWORD=password
         MYSQL_INITDB_SKIP_TZINFO=yes
         XTRABACKUP_PASSWORD=password
         CLUSTER_NAME=terracluster
         CLUSTER_JOIN=pxc_node0
         name=pxc_node1
         net=terra_network
         PXC_ENCRYPT_CLUSTER_TRAFFIC=0
       ports:
         - "33061:3306"
       networks:
         - name: terra_network
